### PR TITLE
Prevents error when testing

### PR DESCRIPTION
**Pull request by jayporta**
This time I didn't run the build script

### CODE REVIEW

**Comment by Akryum** [comment]
The file you changed are part of the build 😉

**Comment by jayporta** [comment]
Ok so how do we fix this? It's a blocker for running unit tests.

**Comment by Akryum** [comment]
You either wait for me to publish a new version (which will happen soon), or you clone the repo and build it locally (and use linking to your project). 😸

**Comment by jayporta** [comment]
I've already done the latter, I just wanted to help even though it was a
small thing.

Thanks

**Pull request closed without merging**
