### PR TITLE
fix: Add optional typescript peerDependency to apollo-composable package

### LINKED ISSUE #1499: Missing peer dependency on typescript in @vue/apollo-composable
**Describe the bug**
When installing this project as dependency through Yarn (v2+), a warning is raised about a missing peer dependency for `typescript`.

See also https://yarnpkg.com/advanced/error-codes#yn0002---missing_peer_dependency (and https://dev.to/arcanis/implicit-transitive-peer-dependencies-ed0).

**To Reproduce**
1. (any empty directory)
1. `yarn set version berry`
1. `yarn add @vue/apollo-composable`

The following message appears;
```
YN0002: │ @vue/apollo-composable@npm:4.0.0-beta.8 [dc3fc] doesn't provide typescript (p70fa5), requested by ts-essentials
```

**Expected behavior**
No warnings.

**Versions**
@vue/apollo-composable: 4.0.0-beta.8

**Additional context**
This can be resolved by adding `typescript` as (optional) peer dependency through the `package.json` of this package.
Also, the warning can be silenced locally by adding the following to a local `.yarnrc.yml` file:
```yml
packageExtensions:
  "@vue/apollo-composable@*":
    peerDependencies:
      typescript: "*"
```

### PR DESCRIPTION
**Pull request by jnoordsij**
Fixes #1499

### CODE REVIEW

**Comment by nickmessing** [comment]
@jnoordsij, This is probably not the correct fix. This project can and is used by some people with plain JS. We should not add typescript as a peerDependency

**Comment by jnoordsij** [comment]
Hey there, thanks for checking this! I do think this is the correct fix for this case, given
- `ts-essentials` is listed as a (*hard*) dependency, although this is also only required for those using TypeScript
- given that `ts-essentials` requires a (very broad but technically speaking still a) specific range of TypeScript versions and lists this as `peerDependency`, it is up to this package to fulfill that in some way
- by explicitly marking it here as an *optional* `peerDependency`, it is up to the end-user to decide on wether or not to use TypeScript, therefore not adding an additional package (even though `ts-essentials` still is added)

The only alternative I see is moving `ts-essentials` to be an optional `peerDependency`, but I think that is more breaking and invasive to end-users, given that it is harder to realise that they should be providing that in case they are using TypeScript, compared to them installing `typescript` when they want to use TypeScript.

**Comment by nickmessing** [comment]
@jnoordsij, oh, didn't realise that `ts-essentials` is a dependency O_O.

@Akryum wdyt on this?

**Comment by jnoordsij** [comment]
As `ts-essentials` now has its `typescript` dependency marked as optional (see https://github.com/ts-essentials/ts-essentials/pull/371), this is no longer required to fix the issue. One may opt to still add this as some possibly useful metadata, although maybe having it at `ts-essentials` and leaving it there suffices. So feel free to close this if there's no time or reason to review/merge this further.

**Pull request closed without merging**
