### PR TITLE
Enhancement: Pass refetch method to query component result

### PR DESCRIPTION
**Pull request by alexandrusavin**
This will pass `refetch` method to the slot scope of query component like this:
```html
<apollo-query>
  <template slot-scope="{ result: { loading, error, data, refetch } }">
    <div>{{data}}</div>
    <button v-on:click="refetch">Reload the data</button>
  </template>
</apollo-query>
```

PS: I need some guidance into how I can run the tests. I tried but I'm getting into dependency mayham.

### CODE REVIEW

**Comment by alexandrusavin** [comment]
This implements the feature request https://github.com/Akryum/vue-apollo/issues/423

**Comment by alukos** [comment]
seems enough access to `query` https://github.com/Akryum/vue-apollo/issues/423#issuecomment-468608771

**Comment by alexandrusavin** [comment]
It would be highly appreciated if one of the maintainers has a look over it and give some feedback.

**Comment by Akryum** [comment]
This was mostly a documentation issue, closed by 1824dcebbfa613037887e585598caabbcec4597c

**Pull request closed without merging**
