### PR TITLE
Improve IE support by not using `for...of`

### PR DESCRIPTION
**Pull request by scq**
`for...of` requires some heavy-duty polyfilling in IE 11 (Symbol and Array.prototype[Symbol.iterator] polyfills) which is unfortunate because this library otherwise works great in IE 11 with some lightweight polyfills for Object.entries() etc - any chance we could just use plain forEach/for?

I believe this would also solve #270.

### CODE REVIEW

**Comment by Akryum** [comment]
The library is already transpiled by babel, so maybe there is an issue with the configuration. I don't want to change the source code to old JavaScript just for the sake of supporting IE. This has to be taken cared of by the build toolchain.

**Comment by scq** [comment]
Ah, yeah... the issue is that `for...of` isn't just syntax (which Babel can transpile) but also involves a new JS API, `Symbol.iterator`, which [babel can't transpile and must be polyfilled](https://medium.com/hackernoon/polyfills-everything-you-ever-wanted-to-know-or-maybe-a-bit-less-7c8de164e423).

The problem is that polyfilling Symbol.iterator is [quite weighty](https://daverupert.com/2017/10/for-of-loops-are-bad/).

It looks like there are some options in https://babeljs.io/docs/en/next/babel-plugin-transform-for-of that could fix this - either `assumeArray`, which assumes that all usages of `for...of` are with arrays, or `loose`, which special cases arrays. Either of these would avoid using Symbol.iterator, so long as `for...of` is only used with arrays or array-like objects.

Want me to create a new PR with that instead?

**Comment by Akryum** [comment]
Sure!

**Comment by scq** [comment]
Great! New PR is #183, will close this one.

**Pull request closed without merging**
