### PR TITLE
The typings for DollarApollo where missing `getClient`

### PR DESCRIPTION
**Pull request by M-Zuber**
I could not find any existing discussion on whether this field should be included or not. But the code base indicates it exists :)

### CODE REVIEW

**Comment by Austio** [comment]
:+1:

**Comment by Akryum** [comment]
It's currently an undocumented method, will merge when it will be the case.

**Comment by M-Zuber** [comment]
I have added minimal documentation, please let me know if there is anything you would like me to add

**Comment by Akryum** [comment]
:+1:

**Pull request merged**
