### PR TITLE
Simple & fast way of querying data (#83)

### PR DESCRIPTION
**Pull request by dimitri-koenig**
See #83

### CODE REVIEW

**Comment by Samuell1** [comment]
This is cool! But there needs to be a global variable how to enabled/disabled it because i importing `*.graphql` files into query then i doesnt need `gql`

**Comment by dimitri-koenig** [comment]
Hm, how does importing graphql files affect this additional non-breaking change/improvement? Why adding a global switch for a feature which could not possibly be used before and is therefore totally optional?

**Comment by Samuell1** [comment]
If you use webpack you can separate queries from logic in files http://dev.apollodata.com/react/webpack.html , then i can simply import file what i need to use in query

**Comment by dimitri-koenig** [comment]
So it's more about wether you want to import gql or not, right?

What about lazy requiring gql?

**Pull request closed without merging**
